USE adlister_db;

DROP TABLE IF EXISTS ads;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(128) NOT NULL ,
    email VARCHAR(128) NOT NULL ,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS ads (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL ,
    title VARCHAR(128) NOT NULL ,
    description VARCHAR(300) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);